if exist .\..\RIDE\STM32100E-EVAL\SysTick.hex (hex2bin.exe  .\..\RIDE\STM32100E-EVAL\SysTick.hex)
if exist .\..\RIDE\STM32100B-EVAL\SysTick.hex (hex2bin.exe  .\..\RIDE\STM32100B-EVAL\SysTick.hex)
if exist .\..\RIDE\STM3210C-EVAL\SysTick.hex (hex2bin.exe  .\..\RIDE\STM3210C-EVAL\SysTick.hex)
if exist .\..\RIDE\STM3210E-EVAL\SysTick.hex (hex2bin.exe  .\..\RIDE\STM3210E-EVAL\SysTick.hex)
if exist .\..\RIDE\STM3210B-EVAL\SysTick.hex (hex2bin.exe  .\..\RIDE\STM3210B-EVAL\SysTick.hex)
if exist .\..\RIDE\STM3210E-EVAL_XL\SysTick.hex (hex2bin.exe  .\..\RIDE\STM3210E-EVAL_XL\SysTick.hex)
if exist .\..\HiTOP\STM32100E-EVAL\Project.hex  (hex2bin.exe  .\..\HiTOP\STM32100E-EVAL\Project.hex)
if exist .\..\HiTOP\STM32100B-EVAL\Project.hex  (hex2bin.exe  .\..\HiTOP\STM32100B-EVAL\Project.hex)
if exist .\..\HiTOP\STM3210B-EVAL\Project.hex  (hex2bin.exe  .\..\HiTOP\STM3210B-EVAL\Project.hex)
if exist .\..\HiTOP\STM3210C-EVAL\Project.hex  (hex2bin.exe  .\..\HiTOP\STM3210C-EVAL\Project.hex)
if exist .\..\HiTOP\STM3210E-EVAL\Project.hex  (hex2bin.exe  .\..\HiTOP\STM3210E-EVAL\Project.hex)
if exist .\..\HiTOP\STM3210E-EVAL_XL\Project.hex  (hex2bin.exe  .\..\HiTOP\STM3210E-EVAL_XL\Project.hex)
if exist .\..\HiTOP\STM32100E-EVAL\Project.hex  (hex2bin.exe  .\..\HiTOP\STM32100E-EVAL\Project.hex)
pause
